# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: thumbnail
val_db_name: thumbnail
num_classes: 23
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 512
# batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
